### ISSUE TITLE
Determine optimal number of subpopulations to fit the data

### ISSUE THREAD

**Issue by ryanspurrell** [CANBOTS/COVID-HMM#2]
```[tasklist]
### Tasks
- [ ] https://github.com/CANBOTS/COVID-HMM/issues/1
- [ ] Fix the BIC score function to determine number of distributions
- [ ] Implement other methods, compare performance to BIC
```
Other methods to determine the number of latent sub populations in the data can be added once the BIC score is fixed, and when the model is actually producing results (currently, the model is producing a bad output)
